boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 8a810d08-f13a-4901-60c9-5c9ac943810c
  sha: sha256:47f11c8844e579d02691a607fbd32540104a9ac7a2534a8ddaef50daf502baac
check/check-0.9.13.tar.gz:
  size: 752880
  object_id: f67fce51-7430-4e61-7676-badef38cf33b
  sha: sha256:ca6589c34f9c60ffd4c3e198ce581e944a9f040ca9352ed54068dd61bebb5cb7
cipher_finder/cipher_finder.jar:
  size: 22062037
  object_id: 10517f38-0b49-437f-7128-245a25d2babd
  sha: sha256:afb4bc5e13d59e0ec7932aed7e6f56edafdbfec0edcb1409737a3407653153cc
cli/cf-cli_6.36.1_linux_x86-64.tgz:
  size: 5910456
  object_id: d9bab44e-781f-438c-722f-2198de17fc37
  sha: sha256:d5e59258183939305f44c471dab41a000290446399cc9b206b107c7bdb8ce180
galera/galera-25.3.28.tar.gz:
  size: 3390722
  object_id: 1229028f-ddde-4f35-69c5-a78c36831689
  sha: sha256:29a627c357562a892d1b31854667c8465fbcedbf81471cb00f08afa33aeccfeb
mariadb/mariadb-10.3.22.tar.gz:
  size: 72050820
  object_id: 143fb366-e9e3-42fb-79a0-841b9867c537
  sha: sha256:3200055dbdc27746981b3bb4bc182e2cb79dcf28ea88014b641a5b81280ccec7
mysqlclient/mariadb-connector-c-3.1.7-src.tar.gz:
  size: 742923
  object_id: c254aaa5-0264-4d77-50b2-589fa7861bc4
  sha: sha256:64f7bc8f5df3200ba6e3080f68ee4942382a33e8371baea8ca4b9242746df59a
pcre-8.35.tar.gz:
  size: 1996552
  object_id: 49abeda0-df2b-404f-775b-d1b4c899e8ff
  sha: sha256:1c9ee292943ba2737f127b481a3f72f44c13fbd09a7b5b4eb8fa58650cfa56a0
python/Python-2.7.13.tgz:
  size: 17076672
  object_id: 2720e9bd-6c4a-4b86-46c5-4550536fd749
  sha: sha256:a4f05a0720ce0fd92626f0278b6b433eee9a6173ddf2bced7957dfb599a5ece1
ruby/ruby-2.3.8.tar.gz:
  size: 17858806
  object_id: 22063eca-b499-46d6-7178-57cfe11554f5
  sha: sha256:b5016d61440e939045d4e22979e04708ed6c8e1c52e7edb2553cf40b73c59abf
ruby/rubygems-2.7.6.tgz:
  size: 852486
  object_id: ddf84287-740f-4446-76e9-26941beaa845
  sha: sha256:67f714a582a9ce471bbbcb417374ea9cf9c061271c865dbb0d093f3bc3371eeb
ruby/yaml-0.1.7.tar.gz:
  size: 527518
  object_id: 619cf88e-a1cb-461c-6ddd-daa7ede36d35
  sha: sha256:8088e457264a98ba451a90b8661fcb4f9d6f478f7265d48322a196cec2480729
scons/scons-2.3.1.tar.gz:
  size: 499037
  object_id: d75793e7-201f-4258-7ec9-021002c2acad
  sha: sha256:091ab468f8e6084c30f3ae9fd48828e3884021401cfef4b713d13161ba120201
socat/socat-1.7.3.2.tar.gz:
  size: 611707
  object_id: e11010b3-becd-4c08-787c-dbf02005ebb4
  sha: sha256:ce3efc17e3e544876ebce7cd6c85b3c279fda057b2857fcaaf67b9ab8bdaf034
